language: ruby
rvm:
  2.0.0
  2.1.0
env:
  # DB=mysql
addons:
  postgresql: "9.3"

before_script:
  - sudo apt-get update
  - sudo apt-get install language-pack-es
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
  - psql -c 'create database p_dev;' -U postgres
  - psql -c 'create database p_test;' -U postgres
  - psql -c 'create database p_pro;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

gemfile:
  Gemfile